---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "helm.fullname" . }}-admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "helm.fullname" . }}-admin
  minReplicas: 2
  maxReplicas: 4
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 3000
  # - type: Pods
  #   pods:
  #     metricName: packets-per-second
  #     targetAverageValue: 1k
