default: &default
  geocoding:
    #ak: BjmmiIn5zKFkW7xBWhNaQ0feUnO63bqe
    ak: ucfWTaf7DcQXMqw221Nf64DGT7aIandO
    sk:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default