---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "helm.fullname" . }}-api
  labels:
    app: {{ template "helm.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ template "helm.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: railsconfig
        secret:
          secretName: {{ .Values.rails_config }}
      - name: shared-data
        emptyDir: {}
      - name: public-dir
        persistentVolumeClaim:
          claimName: imolin-pvc
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end}}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # command: ['sleep', '99999']
        command: ['./entrypoint.sh', 'bundle', 'exec', 'rails', 's', '-b', '0.0.0.0', '-p', '80']
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 600Mi
        volumeMounts:
        - name: railsconfig
          mountPath: /etc/railsconfig
          readOnly: true
        - mountPath: /srv/cms-templates
          name: shared-data
        - mountPath: /srv/app/public/ckeditor_assets
          name: public-dir
          subPath: ckeditor-assets
        - mountPath: /srv/app/public/photos
          name: public-dir
          subPath: photos
        - mountPath: /srv/app/public/attachments
          name: public-dir
          subPath: attachments
        - mountPath: /srv/app/public/system
          name: public-dir
          subPath: system
        env:
        - name: RAILS_ENV
          value: production
        - name: API_ONLY
          value: 'true'
      initContainers:
      - name: cms-template
        image: docker.corp.tanmer.com/tanmer/cms-templates
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /srv/shared-data
          name: shared-data
        command: ['cp', '-r', '.', '/srv/shared-data/']
