#= require vue.setup
#= require admin/sessions
#= require admin/weixin_sessions
#= require admin/bind_weixin
#= require admin/catalogs
#= require admin/products
#= require admin/material_managements
#= require admin/materials
#= require admin/order
#= require admin/produces
#= require admin/audit
#= require admin/role
#= require admin/user
#= require admin/site
#= require admin/finance_history
#= require admin/baidu_map
#= require admin/audit_statistics
#= require select2
#= require select2_locale_zh-CN
#= require select2_js
#= require tracker
# can't require tree
# require_tree .
