#!/bin/sh

set -e

cat << EOS > /srv/dagle/config/application.yml
PROJECT_NAME: ${PROJECT_NAME}
POSTGRESQL_DATABASE_HOST: ${POSTGRESQL_DATABASE_HOST}
POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME}
POSTGRESQL_DATABASE_USERNAME: ${POSTGRESQL_DATABASE_USERNAME}
POSTGRESQL_DATABASE_PASSWORD: ${POSTGRESQL_DATABASE_PASSWORD}
SECRET_KEY_BASE: ${SECRET_KEY_BASE}
REDIS_URL: ${REDIS_URL}
EOS

echo ${SETTINGS_YML} > /srv/dagle/config/settings.${PROJECT_NAME}.yml

bundle exec rails db:create db:migrate db:seed
