apiVersion: v1
kind: Service
metadata:
  name: imolin-dagle-admin
  labels:
    app: dagle-admin
    chart: dagle-0.1.0
    release: imolin
    heritage: Tiller
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: dagle-admin
    release: imolin
