# Default values for sso.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
maxReplicas: 4
image:
  repository: docker.corp.tanmer.com/tanmer/fang-lite
  tag: master-dcd56b0
  pullPolicy: IfNotPresent
  # pullPolicy: Always
  pullSecrets:
  - name: tanmer-docker
service:
  name: rails
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - renju.zhidak.com
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30s"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  tls:
  - hosts:
    - renju.zhidak.com
    # Secrets must be manually created in the namespace.
    secretName: renju-tls
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 400Mi
  requests:
    cpu: 10m
    memory: 128Mi
jobs: {}

rails_config: renju-config
